marttiphpbb_calendarmonthview_redirect_controller:
    pattern: /calendar
    defaults: { _controller: marttiphpbb.calendarmonthview.redirect_controller:redirect }
    requirements:
        _method: GET

marttiphpbb_calendarmonthview_controller:
    pattern: /calendarmonthview/{year}/{month}
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:show }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$
