marttiphpbb_calendarmonthview_defaultview_controller:
    pattern: /calendarmonthview
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:defaultview }
    requirements:
        _method: GET

marttiphpbb_calendarmonthview_yearview_controller:
    pattern: /calendarmonthview/{year}
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:yearview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$

marttiphpbb_calendarmonthview_monthview_controller:
    pattern: /calendarmonthview/{year}/{month}
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:monthview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$

