marttiphpbb_calendarmonthview_redirect_controller:
    pattern: /calendar
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:redirect }
    requirements:
        _method: GET

marttiphpbb_calendarmonthview_page_controller:
    pattern: /calendar/{year}/{month}
    defaults: { _controller: marttiphpbb.calendarmonthview.controller:page }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$
