services:
    marttiphpbb.calendarmonthview.main_listener:
        class: marttiphpbb\calendarmonthview\event\main_listener
        arguments:
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarmonthview.render.links'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmonthview.tag_listener:
        class: marttiphpbb\calendarmonthview\event\tag_listener
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmonthview.store:
        class: marttiphpbb\calendarmonthview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendarmonthview.controller:
        class: marttiphpbb\calendarmonthview\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.calendarmonthview.core.event_container'
            - '@marttiphpbb.calendarmonthview.timeformat'
            - '@marttiphpbb.calendarmonthview.render.render_settings'
            - '@marttiphpbb.calendarmonthview.render.pagination'

    marttiphpbb.calendarmonthview.redirect_controller:
        class: marttiphpbb\calendarmonthview\controller\redirect
        arguments:
            - '@auth'
            - '@user'
            - '@controller.helper'

    marttiphpbb.calendarmonthview.core.event_container:
        class: marttiphpbb\calendarmonthview\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarmonthview.render.render_settings:
        class: marttiphpbb\calendarmonthview\render\render_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.calendarmonthview.render.pagination:
        class: marttiphpbb\calendarmonthview\render\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    marttiphpbb.calendarmonthview.render.tag:
        class: marttiphpbb\calendarmonthview\render\tag
        arguments:
            - '@controller.helper'
            - '@marttiphpbb.calendarmonthview.dateformat'

    marttiphpbb.calendarmonthview.render.posting:
        class: marttiphpbb\calendarmonthview\render\posting
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarmonthview.render.input_settings'
            - '@marttiphpbb.calendarmonthview.render.include_assets'

    marttiphpbb.calendarmonthview.dateformat:
        class: marttiphpbb\calendarmonthview\util\dateformat
        arguments:
            - '@user'
            - '@language'
