services:
    marttiphpbb.calendarmonthview.main_listener:
        class: marttiphpbb\calendarmonthview\event\main_listener
        arguments:
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmonthview.tag_listener:
        class: marttiphpbb\calendarmonthview\event\tag_listener
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmonthview.store:
        class: marttiphpbb\calendarmonthview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendarmonthview.controller:
        class: marttiphpbb\calendarmonthview\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.calendarmonthview.core.event_container'
            - '@marttiphpbb.calendarmonthview.pagination'

    marttiphpbb.calendarmonthview.redirect_controller:
        class: marttiphpbb\calendarmonthview\controller\redirect
        arguments:
            - '@auth'
            - '@user'
            - '@controller.helper'

    marttiphpbb.calendarmonthview.core.event_container:
        class: marttiphpbb\calendarmonthview\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarmonthview.pagination:
        class: marttiphpbb\calendarmonthview\util\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
